module FileData
  # Contains tag number to name information taken from the exif spec
  module ExifTags
    EXIF =
      {
        256 => 'Image.Structure.Width',
        257 => 'Image.Structure.Length',
        258 => 'Image.Structure.BitsPerSample',
        259 => 'Image.Structure.Compression',
        262 => 'Image.Structure.PhotometricInterpretation',
        274 => 'Image.Structure.Orientation',
        277 => 'Image.Structure.SamplesPerPixel',
        284 => 'Image.Structure.PlanarConfiguration',
        530 => 'Image.Structure.YCbCrSubSampling',
        531 => 'Image.Structure.YCbCrPositioning',
        283 => 'Image.Structure.YResolution',
        296 => 'Image.Structure.ResolutionUnit',

        273 => 'Recording.StripOffsets',
        278 => 'Recording.RowsPerStrip',
        279 => 'Recording.StripByteCounts',
        513 => 'Recording.JPEGInterchangeFormat',
        514 => 'Recording.JPEGInterchangeFormatLength',

        301 => 'Image.Data.TransferFunction',
        318 => 'Image.Data.WhitePoint',
        319 => 'Image.Data.PrimaryChromaticities',
        529 => 'Image.Data.YCbCrCoefficients',
        532 => 'Image.Data.ReferenceBlackWhite',

        306 => 'Other.DateTime',
        270 => 'Other.ImageDescription',
        271 => 'Other.Make',
        272 => 'Other.Model',
        305 => 'Other.Software',
        315 => 'Other.Artist',
        33_432 => 'Other.Copyright',

        36_864 => 'Exif.Version.ExifVersion',
        40_960 => 'Exif.Version.FlashpixVersion',

        40_961 => 'Exif.ColorSpace.ColorSpace',
        42_240 => 'Exif.ColorSpace.Gamma',

        40_962 => 'Exif.Configuration.PixelXDimension',
        40_963 => 'Exif.Configuration.PixelYDimension',
        37_121 => 'Exif.Configuration.ComponentsConfiguration',
        37_122 => 'Exif.Configuration.CompressedBitsPerPixel',
        37_500 => 'Exif.Configuration.MakerNote',
        37_510 => 'Exif.Configuration.UserComment',

        40_964 => 'Exif.RelatedFile.RelatedSoundFile',

        36_867 => 'Exif.DateAndTime.DateTimeOriginal',
        36_868 => 'Exif.DateAndTime.DateTimeDigitized',
        37_520 => 'Exif.DateAndTime.SubsecTime',
        37_521 => 'Exif.DateAndTime.SubsecTimeOriginal',
        37_522 => 'Exif.DateAndTime.SubsecTimeDigitized',

        33_434 => 'Exif.PictureTakingConditions.ExposureTime',
        33_437 => 'Exif.PictureTakingConditions.FNumber',
        34_850 => 'Exif.PictureTakingConditions.ExposureProgram',
        34_852 => 'Exif.PictureTakingConditions.SpectralSensitivity',
        34_855 => 'Exif.PictureTakingConditions.PhotographicSensitivity',
        34_856 => 'Exif.PictureTakingConditions.OECF',
        34_864 => 'Exif.PictureTakingConditions.SensitivityType',
        34_865 => 'Exif.PictureTakingConditions.StandardOutputSensitivity',
        34_866 => 'Exif.PictureTakingConditions.RecommendedExposureIndex',
        34_867 => 'Exif.PictureTakingConditions.ISOSpeed',
        34_868 => 'Exif.PictureTakingConditions.ISOSpeedLatitudeyyy',
        34_869 => 'Exif.PictureTakingConditions.ISOSpeedLatitudezzz',
        37_377 => 'Exif.PictureTakingConditions.ShutterSpeedValue',
        37_378 => 'Exif.PictureTakingConditions.ApertureValue',
        37_379 => 'Exif.PictureTakingConditions.BrightnessValue',
        37_380 => 'Exif.PictureTakingConditions.ExposureBiasValue',
        37_381 => 'Exif.PictureTakingConditions.MaxApertureValue',
        37_382 => 'Exif.PictureTakingConditions.SubjectDistance',
        37_383 => 'Exif.PictureTakingConditions.MeteringMode',
        37_384 => 'Exif.PictureTakingConditions.LightSource',
        37_385 => 'Exif.PictureTakingConditions.Flash',
        37_396 => 'Exif.PictureTakingConditions.SubjectArea',
        37_386 => 'Exif.PictureTakingConditions.FocalLength',
        41_483 => 'Exif.PictureTakingConditions.FlashEnergy',
        41_484 => 'Exif.PictureTakingConditions.SpatialFrequencyResponse',

        41_486 => 'Exif.PictureTakingConditions.FocalPlaneXResolution',
        41_487 => 'Exif.PictureTakingConditions.FocalPlaneYResolution',
        41_488 => 'Exif.PictureTakingConditions.FocalPlanResolutionUnit',
        41_492 => 'Exif.PictureTakingConditions.SubjectLocation',
        41_493 => 'Exif.PictureTakingConditions.ExposureIndex',
        41_495 => 'Exif.PictureTakingConditions.SensingMode',
        41_728 => 'Exif.PictureTakingConditions.FileSource',
        41_729 => 'Exif.PictureTakingConditions.SceneType',
        41_730 => 'Exif.PictureTakingConditions.CFAPattern',
        41_985 => 'Exif.PictureTakingConditions.CustomRendered',
        41_986 => 'Exif.PictureTakingConditions.ExposureMode',
        41_987 => 'Exif.PictureTakingConditions.WhiteBalance',
        41_988 => 'Exif.PictureTakingConditions.DigitalZoomRatio',
        41_989 => 'Exif.PictureTakingConditions.FocalLengthIn35mmFilm',
        41_990 => 'Exif.PictureTakingConditions.SceneCaptureType',
        41_991 => 'Exif.PictureTakingConditions.GainControl',
        41_992 => 'Exif.PictureTakingConditions.Contrast',
        41_993 => 'Exif.PictureTakingConditions.Saturation',
        41_994 => 'Exif.PictureTakingConditions.Sharpness',
        41_995 => 'Exif.PictureTakingConditions.DeviceSettingDescription',
        41_996 => 'Exif.PictureTakingConditions.SubjectDistanceRange'
      }.freeze
  end
end
